language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dbeken85/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test-
#docker run dbeken85/react-test npm test -- --coverage

after_success:
  - docker build -t dbeken85/multi-client ./client
  - docker build -t dbeken85/multi-nginx  ./nginx
  - docker build -t dbeken85/multi-server ./server
  - docker build -t dbeken85/multi-worker ./worker
  #Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dbeken85/multi-client
  - docker push dbeken85/multi-nginx
  - docker push dbeken85/multi-server
  - docker push dbeken85/multi-worker
