language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dbeken85/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dbeken85/react-test npm test-
#docker run $DOCKER_ID/react-test npm test -- --coverage

after_success:
  - docker build -t $DOCKER_ID/multi-client ./client
  - docker build -t $DOCKER_ID/multi-nginx  ./nginx
  - docker build -t $DOCKER_ID/multi-server ./server
  - docker build -t $DOCKER_ID/multi-worker ./worker
  #Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push $DOCKER_ID/multi-client
  - docker push $DOCKER_ID/multi-nginx
  - docker push $DOCKER_ID/multi-server
  - docker push $DOCKER_ID/multi-worker
